'use client';

import React, { createContext, useContext, useState, ReactNode } from 'react';
import { SupportedLanguage, LanguageOption } from '../types/clinical';

export const LANGUAGE_OPTIONS: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧', isMvpFull: true },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇮🇳', isMvpFull: true },
  { code: 'th', name: 'Thanglish', nativeName: 'Thanglish (Tamil+English)', flag: '🗣️', isMvpFull: true },
  { code: 'hi', name: 'Hindi', nativeName: 'हिंदी', flag: '🇮🇳' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', flag: '🇮🇳' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', flag: '🇮🇳' },
  { code: 'kn', name: 'Kannada', nativeName: 'கன்னட / ಕನ್ನಡ', flag: '🇮🇳' },
];

export const TRANSLATIONS: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    appTitle: 'ClinAssist',
    tagline: 'AI-Powered Clinical Case-Taking & Decision Support System',
    startNewCase: 'Start New Case',
    existingPatient: 'Existing Patient',
    practitionerLogin: 'Practitioner Login',
    languageSelector: 'Select Language',
    patientRegistration: 'Patient Registration',
    patientId: 'Patient ID',
    name: 'Full Name',
    age: 'Age',
    gender: 'Gender',
    phone: 'Phone Number',
    preferredLanguage: 'Preferred Language',
    emergencyContact: 'Emergency Contact',
    consentLabel: 'I give consent for AI-assisted clinical intake and data processing for healthcare consultation.',
    registerSubmit: 'Proceed to Case-Taking',
    caseTaking: 'Clinical Intake & Case Taking',
    chiefComplaint: 'Chief Complaint',
    voiceInput: 'Voice Input',
    textInput: 'Text Input',
    startRecording: 'Start Recording',
    stopRecording: 'Stop Recording',
    recordingActive: 'Listening to patient...',
    speakNowPrompt: 'Speak clearly into the microphone in your preferred language...',
    conversationHistory: 'Intake Conversation Stream',
    send: 'Send',
    adaptiveQuestions: 'ClinAssist AI Adaptive Questions',
    structuredSymptoms: 'Structured Clinical Symptoms',
    complaint: 'Complaint',
    duration: 'Duration',
    severity: 'Severity (1-10)',
    location: 'Location',
    associatedSymptoms: 'Associated Symptoms',
    pastHistory: 'Past Medical History',
    currentMedications: 'Current Medications',
    editSymptoms: 'Edit Symptoms',
    medicalOCR: 'Medical Document & Prescription Scanner (OCR)',
    uploadDoc: 'Upload Prescription or Lab Report',
    dragDrop: 'Drag and drop medical documents (PNG, JPG, PDF) or click to browse',
    extractText: 'Extract Clinical Text',
    verifiedByPractitioner: 'Practitioner Verified',
    medicalTimeline: 'Patient Medical Timeline',
    clinicalReview: 'Clinical Review & Red Flags',
    redFlagsNotice: 'Information requiring clinical review',
    noAutoDiagnosis: 'Diagnosis is not automatically declared. Practitioner verification required.',
    aiCaseSummary: 'AI Case Summary Synthesis',
    practitionerDashboard: 'Practitioner Clinical Dashboard',
    finalCaseSheet: 'Final Clinical Case Sheet',
    totalPatients: 'Total Patients',
    todayCases: "Today's Cases",
    pendingReviews: 'Pending Reviews',
    completedCases: 'Completed Cases',
    generatePDF: 'Generate & Download PDF Case Sheet',
    saveCase: 'Save Case Sheet',
    signOff: 'Practitioner Sign-off',
    step1Name: '1. Welcome',
    step2Name: '2. Language',
    step3Name: '3. Patient Reg',
    step4Name: '4. Case Taking',
    step5Name: '5. AI Adaptive Qs',
    step6Name: '6. Symptoms',
    step7Name: '7. Document OCR',
    step8Name: '8. Timeline',
    step9Name: '9. Red Flags',
    step10Name: '10. Case Summary',
    step11Name: '11. Dashboard',
    step12Name: '12. Final Case Sheet',
  },
  ta: {
    appTitle: 'ClinAssist',
    tagline: 'செயற்கை நுண்ணறிவு மருத்துவ வழக்கு பதிவு மற்றும் முடிவு உதவி அமைப்பு',
    startNewCase: 'புதிய நோயாளி வழக்கு தொடங்கு',
    existingPatient: 'தற்போதுள்ள நோயாளி',
    practitionerLogin: 'மருத்துவர் உள்நுழைவு',
    languageSelector: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    patientRegistration: 'நோயாளி பதிவு',
    patientId: 'நோயாளி ஐடி',
    name: 'முழு பெயர்',
    age: 'வயது',
    gender: 'பாலினம்',
    phone: 'தொலைபேசி எண்',
    preferredLanguage: 'விருப்ப மொழி',
    emergencyContact: 'அவசர தொடர்பு எண்',
    consentLabel: 'மருத்துவ ஆலோசனைகளுக்காக AI உதவியுடன் கூடிய தகவல்களைப் பயன்படுத்த சம்மதிக்கிறேன்.',
    registerSubmit: 'வழக்கு பதிவுக்கு செல்லவும்',
    caseTaking: 'மருத்துவ வழக்கு தகவல் சேகரிப்பு',
    chiefComplaint: 'முதன்மை குறைபாடு / அறிகுறிகள்',
    voiceInput: 'குரல் பதிவு (Voice Input)',
    textInput: 'எழுத்து பதிவு (Text Input)',
    startRecording: 'பதிவைத் தொடங்கு',
    stopRecording: 'பதிவை நிறுத்து',
    recordingActive: 'நோயாளி கூறுவதைக் கேட்கிறது...',
    speakNowPrompt: 'உங்கள் விருப்ப மொழியில் மைக்ரோஃபோனில் தெளிவாகப் பேசுங்கள்...',
    conversationHistory: 'உரையாடல் வரலாறு',
    send: 'அனுப்பு',
    adaptiveQuestions: 'ClinAssist AI தொடர் கேள்விகள்',
    structuredSymptoms: 'வகைப்படுத்தப்பட்ட மருத்துவ அறிகுறிகள்',
    complaint: 'பிரச்சனை',
    duration: 'கால அளவு',
    severity: 'தீவிரம் (1-10)',
    location: 'பாதிக்கப்பட்ட இடம்',
    associatedSymptoms: 'தொடர்புடைய அறிகுறிகள்',
    pastHistory: 'முந்தைய மருத்துவ வரலாறு',
    currentMedications: 'தற்போதைய மருந்துகள்',
    editSymptoms: 'அறிகுறிகளை திருத்து',
    medicalOCR: 'மருத்துவ ஆவணங்கள் & மருந்துச் சீட்டு ஸ்கேனர் (OCR)',
    uploadDoc: 'மருந்துச் சீட்டு அல்லது பரிசோதனை அறிக்கையை பதிவேற்றவும்',
    dragDrop: 'ஆவணங்களைப் பதிவேற்ற இங்கே இழுக்கவும் (PNG, JPG, PDF)',
    extractText: 'மருத்துவ உரையைப் பிரித்தெடு',
    verifiedByPractitioner: 'மருத்துவரால் சரிபார்க்கப்பட்டது',
    medicalTimeline: 'நோயாளி மருத்துவ வரலாற்று காலவரிசை',
    clinicalReview: 'மருத்துவ ஆய்வு & அவசர எச்சரிக்கைகள் (Red Flags)',
    redFlagsNotice: 'மருத்துவரின் கவனம் தேவைப்படும் தகவல்கள்',
    noAutoDiagnosis: 'தானியங்கி நோய் கண்டறிதல் வழங்கப்படாது. மருத்துவரின் சரிபார்ப்பு அவசியம்.',
    aiCaseSummary: 'AI வழக்கு சுருக்கம் தயாரிப்பு',
    practitionerDashboard: 'மருத்துவர் கட்டுப்பாட்டு அறை (Dashboard)',
    finalCaseSheet: 'இறுதி மருத்துவ வழக்கு அறிக்கை',
    totalPatients: 'மொத்த நோயாளிகள்',
    todayCases: 'இன்றைய வழக்குகள்',
    pendingReviews: 'நிலுவையில் உள்ள ஆய்வுகள்',
    completedCases: 'முடிவுற்ற வழக்குகள்',
    generatePDF: 'PDF அறிக்கையை பதிவிறக்கு',
    saveCase: 'வழக்கை சேமி',
    signOff: 'மருத்துவர் கையொப்பம் / உறுதிப்படுத்தல்',
    step1Name: '1. முகப்பு',
    step2Name: '2. மொழி',
    step3Name: '3. நோயாளி பதிவு',
    step4Name: '4. வழக்கு பதிவு',
    step5Name: '5. AI கேள்விகள்',
    step6Name: '6. அறிகுறிகள்',
    step7Name: '7. ஆவண OCR',
    step8Name: '8. காலவரிசை',
    step9Name: '9. எச்சரிக்கைகள்',
    step10Name: '10. சுருக்கம்',
    step11Name: '11. டாஷ்போர்டு',
    step12Name: '12. இறுதி அறிக்கை',
  },
  th: {
    appTitle: 'ClinAssist',
    tagline: 'AI Medical Case-Taking & Decision Support System (Tamil + English)',
    startNewCase: 'Start New Case / புதிய கேஸ்',
    existingPatient: 'Existing Patient / பழைய பேஷண்ட்',
    practitionerLogin: 'Doctor Login / மருத்துவர் லாகின்',
    languageSelector: 'Select Language / மொழி தேர்வு',
    patientRegistration: 'Patient Registration / பேஷண்ட் ரெஜிஸ்ட்ரேஷன்',
    patientId: 'Patient ID',
    name: 'Full Name / பெயர்',
    age: 'Age / வயது',
    gender: 'Gender / பாலினம்',
    phone: 'Phone Number / போன் நம்பர்',
    preferredLanguage: 'Preferred Language',
    emergencyContact: 'Emergency Contact Number',
    consentLabel: 'I give consent for AI case-taking & healthcare consultation processing.',
    registerSubmit: 'Proceed to Case-Taking / அடுத்து செல்லவும்',
    caseTaking: 'Clinical Case Taking (Voice / Text)',
    chiefComplaint: 'Chief Complaint / என்ன பிரச்சனை?',
    voiceInput: 'Voice Input / வாய்ஸ் பதிவு',
    textInput: 'Text Input / டைப் செய்யவும்',
    startRecording: 'Start Recording / பேசவும்',
    stopRecording: 'Stop Recording / நிறுத்தவும்',
    recordingActive: 'Patient பேசுவதை கேட்கிறது...',
    speakNowPrompt: 'Mic-ல தெளிவா பேசுங்க (e.g. "Enaku 3 days-ah fever iruku")...',
    conversationHistory: 'Conversation Stream / உரையாடல்',
    send: 'Send / அனுப்பு',
    adaptiveQuestions: 'ClinAssist AI Adaptive Questions (தொடர் கேள்விகள்)',
    structuredSymptoms: 'Structured Symptoms / ஒழுங்கமைக்கப்பட்ட அறிகுறிகள்',
    complaint: 'Complaint / பிரச்சனை',
    duration: 'Duration / எத்தனை நாளா?',
    severity: 'Severity / எவ்வளவு அதிகம்? (1-10)',
    location: 'Location / எந்த இடத்தில்?',
    associatedSymptoms: 'Associated Symptoms / வேறு என்ன அறிகுறிகள்?',
    pastHistory: 'Past Medical History / பழைய வியாதிகள்',
    currentMedications: 'Current Medications / சாப்பிடும் மருந்துகள்',
    editSymptoms: 'Edit Symptoms / திருத்தவும்',
    medicalOCR: 'Medical Document & Report Scanner (OCR)',
    uploadDoc: 'Upload Prescription / Prescription அப்லோட் செய்',
    dragDrop: 'Upload image or PDF report here...',
    extractText: 'Extract Text / விவரங்களை பிரித்தெடு',
    verifiedByPractitioner: 'Doctor Verified / மருத்துவரால் சரிபார்க்கப்பட்டது',
    medicalTimeline: 'Patient Medical Timeline / மருத்துவ காலவரிசை',
    clinicalReview: 'Clinical Review & Red Flags (அவசர எச்சரிக்கைகள்)',
    redFlagsNotice: 'Important clinical warning - doctor review needed!',
    noAutoDiagnosis: 'Automatic diagnosis தரப்படாது. Doctor verification கட்டாயம்.',
    aiCaseSummary: 'AI Case Summary Synthesis',
    practitionerDashboard: 'Doctor Dashboard / டாஷ்போர்டு',
    finalCaseSheet: 'Final Clinical Case Sheet / இறுதி அறிக்கை',
    totalPatients: 'Total Patients',
    todayCases: "Today's Cases",
    pendingReviews: 'Pending Reviews',
    completedCases: 'Completed Cases',
    generatePDF: 'Download PDF Case Sheet',
    saveCase: 'Save Case Sheet / சேமிக்கவும்',
    signOff: 'Doctor Sign-off / உறுதிப்படுத்துதல்',
    step1Name: '1. Welcome',
    step2Name: '2. Language',
    step3Name: '3. Patient Reg',
    step4Name: '4. Case Taking',
    step5Name: '5. AI Questions',
    step6Name: '6. Symptoms',
    step7Name: '7. Document OCR',
    step8Name: '8. Timeline',
    step9Name: '9. Red Flags',
    step10Name: '10. Summary',
    step11Name: '11. Dashboard',
    step12Name: '12. Final Case Sheet',
  },
  hi: {
    appTitle: 'ClinAssist',
    tagline: 'एआई-संचालित नैदानिक ​​मामला पंजीकरण और निर्णय सहायता प्रणाली',
    startNewCase: 'नया मामला शुरू करें',
    existingPatient: 'मौजूदा मरीज',
    practitionerLogin: 'चिकित्सक लॉगिन',
    languageSelector: 'भाषा चुनें',
    patientRegistration: 'मरीज पंजीकरण',
    patientId: 'मरीज आईडी',
    name: 'पूरा नाम',
    age: 'उम्र',
    gender: 'लिंग',
    phone: 'फोन नंबर',
    preferredLanguage: 'पसंदीदा भाषा',
    emergencyContact: 'आपातकालीन संपर्क',
    consentLabel: 'मैं स्वास्थ्य देखभाल परामर्श के लिए एआई-सहायता प्राप्त डेटा प्रोसेसिंग की सहमति देता हूं।',
    registerSubmit: 'मामले की कार्यवाही आगे बढ़ाएं',
    caseTaking: 'नैदानिक ​​मामला पंजीकरण',
    chiefComplaint: 'मुख्य शिकायत',
    voiceInput: 'आवाज इनपुट',
    textInput: 'टेक्स्ट इनपुट',
    startRecording: 'रिकॉर्डिंग शुरू करें',
    stopRecording: 'रिकॉर्डिंग रोकें',
    recordingActive: 'सुन रहा है...',
    speakNowPrompt: 'माइक में स्पष्ट रूप से बोलें...',
    conversationHistory: 'बातचीत का इतिहास',
    send: 'भेजें',
    adaptiveQuestions: 'ClinAssist एआई अनुकूली प्रश्न',
    structuredSymptoms: 'संरचित लक्षण',
    complaint: 'शिकायत',
    duration: 'अवधि',
    severity: 'गंभीरता (1-10)',
    location: 'स्थान',
    associatedSymptoms: 'संबंधित लक्षण',
    pastHistory: 'पिछला चिकित्सा इतिहास',
    currentMedications: 'वर्तमान दवाएं',
    editSymptoms: 'लक्षण संपादित करें',
    medicalOCR: 'मेडिकल दस्तावेज़ स्कैनर (OCR)',
    uploadDoc: 'प्रिस्क्रिप्शन या रिपोर्ट अपलोड करें',
    dragDrop: 'दस्तावेज़ यहाँ खींचें और छोड़ें',
    extractText: 'पाठ निकालें',
    verifiedByPractitioner: 'चिकित्सक द्वारा सत्यापित',
    medicalTimeline: 'मरीज की चिकित्सा समयरेखा',
    clinicalReview: 'नैदानिक ​​समीक्षा और रेड फ्लैग',
    redFlagsNotice: 'नैदानिक ​​समीक्षा की आवश्यकता वाली जानकारी',
    noAutoDiagnosis: 'स्वचालित निदान नहीं दिया जाता है। चिकित्सक का सत्यापन आवश्यक है।',
    aiCaseSummary: 'एआई केस सारांश',
    practitionerDashboard: 'चिकित्सक डैशबोर्ड',
    finalCaseSheet: 'अंतिम केस शीट',
    totalPatients: 'कुल मरीज',
    todayCases: 'आज के मामले',
    pendingReviews: 'लंबित समीक्षाएं',
    completedCases: 'पूरे किए गए मामले',
    generatePDF: 'पीडीएफ डाउनलोड करें',
    saveCase: 'केस सहेजें',
    signOff: 'चिकित्सक हस्ताक्षर',
    step1Name: '1. स्वागत',
    step2Name: '2. भाषा',
    step3Name: '3. पंजीकरण',
    step4Name: '4. मामला',
    step5Name: '5. प्रश्न',
    step6Name: '6. लक्षण',
    step7Name: '7. ओसीआर',
    step8Name: '8. समयरेखा',
    step9Name: '9. चेतावनी',
    step10Name: '10. सारांश',
    step11Name: '11. डैशबोर्ड',
    step12Name: '12. केस शीट',
  },
  te: {
    appTitle: 'ClinAssist',
    tagline: 'AI ఆధారిత క్లినికల్ కేసు నమోదు మరియు నిర్ణయ సహాయ వ్యవస్థ',
    startNewCase: 'కొత్త కేసు ప్రారంభించండి',
    existingPatient: 'ప్రస్తుత రోగి',
    practitionerLogin: 'వైద్యుల లాగిన్',
    languageSelector: 'భాషను ఎంచుకోండి',
    patientRegistration: 'రోగి నమోదు',
    patientId: 'రోగి ఐడి',
    name: 'పూర్తి పేరు',
    age: 'వయస్సు',
    gender: 'లింగం',
    phone: 'ఫోన్ నంబర్',
    preferredLanguage: 'అభిమత భాష',
    emergencyContact: 'అత్యవసర పరిచయం',
    consentLabel: 'వైద్య సంప్రదింపుల కోసం AI ఆధారిత సమాచార ప్రాసెసింగ్‌కు సమ్మతిస్తున్నాను.',
    registerSubmit: 'కేసు వివరాలకు వెళ్లండి',
    caseTaking: 'క్లినికల్ కేసు వివరాలు',
    chiefComplaint: 'ముఖ్యమైన సమస్య',
    voiceInput: 'వాయిస్ ఇన్‌పుట్',
    textInput: 'టెక్స్ట్ ఇన్‌పుట్',
    startRecording: 'రికార్డింగ్ ప్రారంభించండి',
    stopRecording: 'రికార్డింగ్ ఆపండి',
    recordingActive: 'వింటోంది...',
    speakNowPrompt: 'మైక్‌లో స్పష్టంగా మాట్లాడండి...',
    conversationHistory: 'సంభాషణ చరిత్ర',
    send: 'పంపండి',
    adaptiveQuestions: 'ClinAssist AI అనుకూల ప్రశ్నలు',
    structuredSymptoms: 'నిర్మాణాత్మక లక్షణాలు',
    complaint: 'సమస్య',
    duration: 'వ్యవధి',
    severity: 'తీవ్రత (1-10)',
    location: 'ప్రాంతం',
    associatedSymptoms: 'సంబంధిత లక్షణాలు',
    pastHistory: 'గత వైద్య చరిత్ర',
    currentMedications: 'ప్రస్తుత మందులు',
    editSymptoms: 'లక్షణాలను సవరించండి',
    medicalOCR: 'మెడికల్ పత్రాల స్కేనర్ (OCR)',
    uploadDoc: 'ప్రిస్క్రిప్షన్ అప్‌లోడ్ చేయండి',
    dragDrop: 'పత్రాలను ఇక్కడ వేయండి',
    extractText: 'టెక్స్ట్‌ను సంగ్రహించండి',
    verifiedByPractitioner: 'వైద్యులు సరిచూశారు',
    medicalTimeline: 'రోగి వైద్య కాలక్రమం',
    clinicalReview: 'క్లినికల్ సమీక్ష మరియు రెడ్ ఫ్లాగ్స్',
    redFlagsNotice: 'వైద్యుల పరిశీలన అవసరమైన వివరాలు',
    noAutoDiagnosis: 'స్వయంచాలక రోగనిర్ధారణ చేయబడదు.',
    aiCaseSummary: 'AI కేసు సారాంశం',
    practitionerDashboard: 'వైద్యుల డాష్‌బోర్డ్',
    finalCaseSheet: 'చివరి కేసు షీట్',
    totalPatients: 'మొత్తం రోగులు',
    todayCases: 'నేటి కేసులు',
    pendingReviews: 'పెండింగ్ సమీక్షలు',
    completedCases: 'పూర్తయిన కేసులు',
    generatePDF: 'PDF డౌన్‌లోడ్ చేయండి',
    saveCase: 'కేసును సేవ్ చేయండి',
    signOff: 'వైద్యుల సంతకం',
    step1Name: '1. స్వాగతం',
    step2Name: '2. భాష',
    step3Name: '3. నమోదు',
    step4Name: '4. కేసు వివరాలు',
    step5Name: '5. ప్రశ్నలు',
    step6Name: '6. లక్షణాలు',
    step7Name: '7. OCR',
    step8Name: '8. కాలక్రమం',
    step9Name: '9. హెచ్చరికలు',
    step10Name: '10. సారాంశం',
    step11Name: '11. డాష్‌బోర్డ్',
    step12Name: '12. కేస్ షీట్',
  },
  ml: {
    appTitle: 'ClinAssist',
    tagline: 'എഐ പിന്തുണയുള്ള ക്ലിനിക്കൽ കേസ് രജിസ്ട്രേഷനും തീരുമാന സഹായ സംവിധാനവും',
    startNewCase: 'പുതിയ കേസ് ആരംഭിക്കുക',
    existingPatient: 'നിലവിലുള്ള രോഗി',
    practitionerLogin: 'ഡോക്ടർ ലോഗിൻ',
    languageSelector: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    patientRegistration: 'രോഗി രജിസ്ട്രേഷൻ',
    patientId: 'രോഗി ഐഡി',
    name: 'മുഴുവൻ പേര്',
    age: 'വയസ്സ്',
    gender: 'ലിംഗം',
    phone: 'ഫോൺ നമ്പർ',
    preferredLanguage: 'താല്പര്യമുള്ള ഭാഷ',
    emergencyContact: 'അടിയന്തര ബന്ധപ്പെടൽ',
    consentLabel: 'ചികിത്സാ ആവശ്യങ്ങൾക്കായി വിവരങ്ങൾ പ്രോസസ്സ് ചെയ്യുന്നതിന് ഞാൻ സമ്മതിക്കുന്നു.',
    registerSubmit: 'കേസ് വിശദാംശങ്ങളിലേക്ക് കടക്കുക',
    caseTaking: 'ക്ലിനിക്കൽ കേസ് വിവരശേഖരണം',
    chiefComplaint: 'പ്രധാന ബുദ്ധിമുട്ട്',
    voiceInput: 'ശബ്ദ ഇൻപുട്ട്',
    textInput: 'ടെക്സ്റ്റ് ഇൻപുട്ട്',
    startRecording: 'റെക്കോർഡിംഗ് ആരംഭിക്കുക',
    stopRecording: 'റെക്കോർഡിംഗ് നിർത്തുക',
    recordingActive: 'ശ്രദ്ധിക്കുന്നു...',
    speakNowPrompt: 'മൈക്രോഫോണിൽ വ്യക്തമായി സംസാരിക്കുക...',
    conversationHistory: 'സംഭാഷണ ചരിത്രം',
    send: 'അയക്കുക',
    adaptiveQuestions: 'ClinAssist എഐ ചോദ്യങ്ങൾ',
    structuredSymptoms: 'വർഗ്ഗീകരിച്ച രോഗലക്ഷണങ്ങൾ',
    complaint: 'പ്രശ്നം',
    duration: 'കാലയളവ്',
    severity: 'തീവ്രത (1-10)',
    location: 'സ്ഥാനം',
    associatedSymptoms: 'ബന്ധപ്പെട്ട ലക്ഷണങ്ങൾ',
    pastHistory: 'മുൻകാല ചികിത്സ ചരിത്രം',
    currentMedications: 'നിലവിലെ മരുന്നുകൾ',
    editSymptoms: 'ലക്ഷണങ്ങൾ തിരുത്തുക',
    medicalOCR: 'മെഡിക്കൽ രേഖകൾ സ്കാനർ (OCR)',
    uploadDoc: 'പ്രિસ્ക്രിപ്ഷൻ അപ്‌ലോഡ് ചെയ്യുക',
    dragDrop: 'രേഖകൾ ഇവിടെ സമർപ്പിക്കുക',
    extractText: 'ടെക്സ്റ്റ് വേർതിരിച്ചെടുക്കുക',
    verifiedByPractitioner: 'ഡോക്ടർ പരിശോധിച്ചു',
    medicalTimeline: 'രോഗിയുടെ മെഡിക്കൽ ടൈംലൈൻ',
    clinicalReview: 'ക്ലിനിക്കൽ അവലോകനവും മുന്നറിയിപ്പുകളും',
    redFlagsNotice: 'ഡോക്ടറുടെ ശ്രദ്ധ ആവശ്യമുള്ള വിവരങ്ങൾ',
    noAutoDiagnosis: 'ഓട്ടോമാറ്റിക് രോഗനിർണ്ണയം നൽകുന്നില്ല.',
    aiCaseSummary: 'എഐ കേസ് സംഗ്രഹം',
    practitionerDashboard: 'ഡോക്ടർ ഡാഷ്‌ബോർഡ്',
    finalCaseSheet: 'അന്തിമ കേസ് ഷീറ്റ്',
    totalPatients: 'ആകെ രോഗികൾ',
    todayCases: 'ഇന്നത്തെ കേസുകൾ',
    pendingReviews: 'തീർപ്പുകൽപ്പിക്കാത്തവ',
    completedCases: 'പൂർത്തിയായവ',
    generatePDF: 'പിഡിഎഫ് ഡൗൺലോഡ് ചെയ്യുക',
    saveCase: 'കേസ് സേവ് ചെയ്യുക',
    signOff: 'ഡോക്ടർ സാക്ഷ്യപ്പെടുത്തൽ',
    step1Name: '1. സ്വാഗതം',
    step2Name: '2. ഭാഷ',
    step3Name: '3. രജിസ്ട്രേഷൻ',
    step4Name: '4. കേസ് വിവരങ്ങൾ',
    step5Name: '5. ചോദ്യങ്ങൾ',
    step6Name: '6. ലക്ഷണങ്ങൾ',
    step7Name: '7. ഒസിആർ',
    step8Name: '8. ടൈംലൈൻ',
    step9Name: '9. മുന്നറിയിപ്പുകൾ',
    step10Name: '10. സംഗ്രഹം',
    step11Name: '11. ഡാഷ്‌ബോർഡ്',
    step12Name: '12. കേസ് ഷീറ്റ്',
  },
  kn: {
    appTitle: 'ClinAssist',
    tagline: 'ಎಐ ಆಧಾರಿತ ವೈದ್ಯಕೀಯ ಪ್ರಕರಣ ದಾಖಲಾತಿ ಮತ್ತು ನಿರ್ಧಾರ ಬೆಂಬಲ ವ್ಯವಸ್ಥೆ',
    startNewCase: 'ಹೊಸ ಪ್ರಕರಣ ಪ್ರಾರಂಭಿಸಿ',
    existingPatient: 'ಹಾಲಿ ರೋಗಿ',
    practitionerLogin: 'ವೈದ್ಯರ ಲಾಗಿನ್',
    languageSelector: 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    patientRegistration: 'ರೋಗಿ ನೋಂದಣಿ',
    patientId: 'ರೋಗಿಯ ಐಡಿ',
    name: 'ಪೂರ್ಣ ಹೆಸರು',
    age: 'ವಯಸ್ಸು',
    gender: 'ಲಿಂಗ',
    phone: 'ಫೋನ್ ಸಂಖ್ಯೆ',
    preferredLanguage: 'ಆದ್ಯತೆಯ ಭಾಷೆ',
    emergencyContact: 'ತುರ್ತು ಸಂಪರ್ಕ',
    consentLabel: 'ವೈದ್ಯಕೀಯ ಸಲಹೆಗಾಗಿ ಎಐ ಪ್ರಕ್ರಿಯೆಗೆ ನಾನು ಒಪ್ಪಿಗೆ ನೀಡುತ್ತೇನೆ.',
    registerSubmit: 'ಪ್ರಕರಣಕ್ಕೆ ಮುಂದುವರಿಯಿರಿ',
    caseTaking: 'ವೈದ್ಯಕೀಯ ವಿವರ ಸಂಗ್ರಹಣೆ',
    chiefComplaint: 'ಮುಖ್ಯ ಸಮಸ್ಯೆ',
    voiceInput: 'ಧ್ವನಿ ಇನ್‌ಪುಟ್',
    textInput: 'ಪಠ್ಯ ಇನ್‌ಪುಟ್',
    startRecording: 'ರೆಕಾರ್ಡಿಂಗ್ ಪ್ರಾರಂಭಿಸಿ',
    stopRecording: 'ರೆಕಾರ್ಡಿಂಗ್ ನಿಲ್ಲಿಸಿ',
    recordingActive: 'ಆಲಿಸುತ್ತಿದೆ...',
    speakNowPrompt: 'ಮೈಕ್‌ನಲ್ಲಿ ಸ್ಪಷ್ಟವಾಗಿ ಮಾತನಾಡಿ...',
    conversationHistory: 'ಸಂಭಾಷಣೆ ಇತಿಹಾಸ',
    send: 'ಕಳುಹಿಸಿ',
    adaptiveQuestions: 'ClinAssist ಎಐ ಪ್ರಶ್ನೆಗಳು',
    structuredSymptoms: 'ವರ್ಗೀಕೃತ ರೋಗಲಕ್ಷಣಗಳು',
    complaint: 'ಸಮಸ್ಯೆ',
    duration: 'ಅವಧಿ',
    severity: 'ತೀವ್ರತೆ (1-10)',
    location: 'ಸ್ಥಳ',
    associatedSymptoms: 'ಸಂಬಂಧಿತ ಲಕ್ಷಣಗಳು',
    pastHistory: 'ಹಿಂದಿನ ವೈದ್ಯಕೀಯ ಇತಿಹಾಸ',
    currentMedications: 'ಪ್ರಸ್ತುತ ಔಷಧಿಗಳು',
    editSymptoms: 'ರೋಗಲಕ್ಷಣಗಳನ್ನು ತಿದ್ದಿ',
    medicalOCR: 'ವೈದ್ಯಕೀಯ ದಾಖಲೆಗಳ ಸ್ಕ್ಯಾನರ್ (OCR)',
    uploadDoc: 'ದಾಖಲೆಯನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    dragDrop: 'ದಾಖಲೆಗಳನ್ನು ಇಲ್ಲಿ ಹಾಕಿ',
    extractText: 'ಪಠ್ಯ ಹೊರತೆಗೆಯಿರಿ',
    verifiedByPractitioner: 'ವೈದ್ಯರು ಪರಿಶೀಲಿಸಿದ್ದಾರೆ',
    medicalTimeline: 'ರೋಗಿಯ ವೈದ್ಯಕೀಯ ಕಾಲಸೂಚಿ',
    clinicalReview: 'ವೈದ್ಯಕೀಯ ಪರಿಶೀಲನೆ ಮತ್ತು ಎಚ್ಚರಿಕೆಗಳು',
    redFlagsNotice: 'ವೈದ್ಯರ ಗಮನ ಅಗತ್ಯವಿರುವ ವಿವರಗಳು',
    noAutoDiagnosis: 'ಸ್ವಯಂಚಾಲಿತ ರೋಗನಿರ್ಣಯ ನೀಡಲಾಗುವುದಿಲ್ಲ.',
    aiCaseSummary: 'ಎಐ ಪ್ರಕರಣದ ಸಾರಾಂಶ',
    practitionerDashboard: 'ವೈದ್ಯರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    finalCaseSheet: 'ಅಂತಿಮ ಪ್ರಕರಣದ ಪತ್ರ',
    totalPatients: 'ಒಟ್ಟು ರೋಗಿಗಳು',
    todayCases: 'ಇಂದಿನ ಪ್ರಕರಣಗಳು',
    pendingReviews: 'ಬಾಕಿ ಪರಿಶೀಲನೆಗಳು',
    completedCases: 'ಪೂರ್ಣಗೊಂಡ ಪ್ರಕರಣಗಳು',
    generatePDF: 'ಪಿಡಿಎಫ್ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    saveCase: 'ಪ್ರಕರಣ ಉಳಿಸಿ',
    signOff: 'ವೈದ್ಯರ ಸಹಿ',
    step1Name: '1. ಸ್ವಾಗತ',
    step2Name: '2. ಭಾಷೆ',
    step3Name: '3. ನೋಂದಣಿ',
    step4Name: '4. ಪ್ರಕರಣ',
    step5Name: '5. ಪ್ರಶ್ನೆಗಳು',
    step6Name: '6. ಲಕ್ಷಣಗಳು',
    step7Name: '7. OCR',
    step8Name: '8. ಕಾಲಸೂಚಿ',
    step9Name: '9. ಎಚ್ಚರಿಕೆಗಳು',
    step10Name: '10. ಸಾರಾಂಶ',
    step11Name: '11. ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    step12Name: '12. ಪ್ರಕರಣ ಪತ್ರ',
  },
};

interface LanguageContextType {
  language: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<SupportedLanguage>('en');

  const t = (key: string): string => {
    return TRANSLATIONS[language]?.[key] || TRANSLATIONS.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
